repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [
          '--ignore=F405,F403,W503'
        ]
        additional_dependencies: [flake8-nb]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
    -   id: isort

-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        exclude: ^(docs/conf.py|setup.py|__init__.py)
        args: [-vv, -i, -I, --fail-under=99, src]
